#!/usr/bin/env bash
# GENERATED by scripts/sync-cursor-plugin.py in vibeshub/vibeshub (do not edit).
# Cursor afterShellExecution wrapper for vibeshub auto-share. Resolves its own
# directory (cwd-independent) so the hook works wherever Cursor runs it, and
# exports the platform so the adapter routes to the Cursor transcript reader.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
export VIBESHUB_PLATFORM=cursor
exec python3 "$here/on-pr-share.py"
